### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by afnanplk** [SkueletorTlg/WhatsAsenaDuplicated#1]

**Comment by SkueletorTlg** [comment]
hi

**Comment by afnanplk** [comment]
does your eva works..?

**Comment by SkueletorTlg** [comment]
I'm not focusing that much on that command, I just copied and pasted, but I think it does work, except for voice chat

**Comment by afnanplk** [comment]
please check i think it does not work, and if it does not work i have solution
